# Generated by Django 3.2.12 on 2023-11-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_center', '0002_auto_20231113_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В работе', 'В работе'), ('Готов', 'Готов'), ('Выдан', 'Выдан'), ('Отклонён', 'Отклонён')], default='Новый', max_length=10),
        ),
    ]
